[package]
name = "dilithiumr"
version = "0.1.0"
edition = "2021"
author = "Hugo PEYRON"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]