[package]
name = "dilithiumr"
version = "0.1.0"
edition = "2021"
author = "Hugo PEYRON"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clippy = "0.0.302"
rand = "0.8.5"
sha3 = "0.10.8"

[features]
